### PR TITLE
discontinue bookshelf

### PR DESCRIPTION
**Pull request by AudreyAltman**
This discontinues the bookshelf feature.  Menu links to the bookshelf have been removed.  If a user directly accesses dp.la/bookshelf, they will see this:

screen shot 2016-06-27 at 11 36 03 am

I've tried to retain any complex logic just in case we or anyone else using the application wants to use it again in the future.

Additional changes include:
- Remove load requirements for bookshelf JavaScript and CSS.
- Remove view logic that assumes presence of bookshelf.
- Remove bookshelf locale variables.
- Retain original view in `app/views/bookshelf/show.html.haml.discontinued`.
- Comment out (as opposed to deleting) original controller logic.

This has been tested locally.  It addresses [ticket #8435](https://issues.dp.la/issues/8435).

### CODE REVIEW

**Comment by markbreedlove** [comment]
Looks like that will work.

If we're keeping files and commented-out code in case someone wants to reinstate it, should we also keep some kind of backup of the lines in various files that were deleted?  It seems that reinstating the bookshelf would require that someone check the revision history anyway and revert those changes; so they might as well revert everything instead of reverting some things and uncommenting others.

**Comment by AudreyAltman** [comment]
@markbreedlove yeah, that's a good point.  I agree that it would be best to comment everything or delete everything.  Which do you think is preferable?

**Comment by markbreedlove** [comment]
@AudreyAltman My vote is to delete everything and let the revision history show what was changed.

**Comment by AudreyAltman** [comment]
@markbreedlove okay, I'll make those changes.  I'll also delete the bookshelf-specific CSS and JavaScript files.

**Comment by AudreyAltman** [comment]
Okay @markbreedlove, I've gone nuclear.  I deleted everything bookshelf-related, including JavaScript, CSS, and image files.  I tested locally, and it looks like everything else is still working just fine.

**Comment by markbreedlove** [comment]
👍  OK!

**Pull request merged**
