### PR TITLE
Add placeholder slide images when private assets are not available

### PR DESCRIPTION
**Pull request by anarchivist**

### CODE REVIEW

**Comment by AudreyAltman** [comment]
Code looks good.  Do you need me to test it by deploying locally or anything?

**Comment by markbreedlove** [comment]
I think this should be good to go, as I recall.  @anarchivist, can you refresh my memory?  Are you reintroducing the same change that was working before the changes to automation [that you reverted](https://github.com/dpla/automation/pull/47)?

**Comment by anarchivist** [comment]
It's not reintroducing the same change, per se.

If someone installs the dependencies using `gem --without dpla_branding`, you won't see broken images.

**Comment by anarchivist** [comment]
Basically, if `DplaFrontendAssets` is *not* defined, it rewrites any matching path for the slider images.

**Comment by markbreedlove** [comment]
Oh, I see.  I hadn't realized that `#branding_img` predates this change.

**Comment by mdellabitta** [comment]
looks like this has merge conflicts now?

**Comment by mdellabitta** [comment]
Oh I see, this has been sitting around for a year... :)

**Pull request closed without merging**
