### PR TITLE
pin all gems to current production versions

### PR DESCRIPTION
**Pull request by AudreyAltman**
This pins all gems to the versions current running in production.

### CODE REVIEW

**Comment by no-reply** [comment]
Do we want to pin to minor, or to tiny versions? 

I'm leaning toward tiny as the more conservative option. It creates overhead in keeping dependencies up to date as minor versions are dropped from support, but I think that's just the reality.

**Comment by AudreyAltman** [comment]
@no-reply okay, I will re-pin to tiny version.

**Comment by AudreyAltman** [comment]
@no-reply pinned to tiny versions!

**Comment by no-reply** [comment]
:+1: LGTM.

I'll give it a bit for others to peek, and merge later today if no one else beats me to it.

**Comment by markbreedlove** [comment]
Looks good to me.

**Pull request merged**
