### PR TITLE
Add canonical tag to item pages

### PR DESCRIPTION
**Pull request by markbreedlove**
Addresses https://issues.dp.la/issues/7730

### CODE REVIEW

**Comment by AudreyAltman** [comment]
This looks good.  My only concern is that it looks like `overwrite_params` was [depreciated in Rails 2.3.8])http://stackoverflow.com/questions/3648433/why-was-overwrite-params-deprecated-in-rails-3).  We might want to see if there's a more future-proof way to to strip params, or at least make a comment so we can address it later.

**Comment by markbreedlove** [comment]
I've redone the change so that it uses `request.original_url` and a simple string `split`. I think this is better because it's more clear at a glance without looking anything up what this actually does.

**Comment by AudreyAltman** [comment]
This is great!  If you squash, I'll merge.

**Comment by markbreedlove** [comment]
OK, all set.

**Pull request merged**
