### PR TITLE
Fix devise and better_errors versions in Gemfile

### PR DESCRIPTION
**Pull request by markbreedlove**
Add specific version limits to devise and better_errors gems, so that they do not upgrade to breaking version numbers, and so that new installations do not run into errors.  The latest version of better_errors wants Ruby 2 (while we are using 1.9), and devise v3+ requires changes to our configuration to avoid errors on startup, and is untested with our application.

A bundle update on an old installation will trigger the errors mentioned above.

### CODE REVIEW

**Comment by AudreyAltman** [comment]
:+1:

**Comment by no-reply** [comment]
:+1:

Two questions:

   - Do we want to pin these to their current minor versions, rather than major? e.g. `~> 0.2.0`
   - Do we want to pin the other gems this project depends on?

If the answer to both of these is either 'no' or 'yes, but later', I'm ready to merge.

**Comment by markbreedlove** [comment]
@no-reply: In the case of devise, yes, it should be limited to highest patch of major version 2, because the breaking change came with version 3.  However, you've made me reconsider the better_errors version.  After looking at that more closely, the Ruby 2 requirement came with version 2 of better_errors, so I'll try to revise this with `gem 'better_errors', '~> 1.0'`

**Comment by markbreedlove** [comment]
I've changed the better_errors version, and it deploys without error.

In either case, I'm adding a restriction where we didn't have any version requirements before.  I'm being as lenient as possible, only preventing a version increase to the point where an error is known to occur.

**Comment by no-reply** [comment]
:+1:

**Pull request merged**
