### PR TITLE
add previous and next buttons to item view

### PR DESCRIPTION
**Pull request by AudreyAltman**
This adds a feature allowing users to page through search results via "Next" and "Previous" buttons on /item pages.

screen shot 2016-07-19 at 1 38 14 pm

If I am on an /item page and I want to get the next item, on a very high level, I need to be able to to reconstruct the context of the search results so I know how to get the next item within that sequence of results.  And, I need to be able to pass that context on so I can get the next-next item and the next-next-next item etc.  More specifically, the "context" I need includes the search query, the position of the item within the search, and the correct page.  The same principle goes for getting the previous item.

To reconstruct the search query, the `items#show` controller method can use the `back_uri` param, which is already in place.  A new param, `next`, holds the position of the next item within the search results.  The page itself can be inferred from the position.  Again, the same general principle goes for getting the previous item.

So the meat of this PR is generating `next` and `previous` params for the `items#show` controller method, and then using the `next`, `previous`, and `back_uri` params to get the next or previous item.

It may be useful to note that the `DPLA::Result` class holds a sequence of items that represents a page of search results.  The `position_after` and `position_before` methods allow you to get the next or previous position of any item within the sequence (or nil if there is no next or previous item).

This does make for a “fat” controller, but to my perspective it doesn’t fit elegantly into any existing models, so I just left it.

This only adds next and previous buttons to items that originate from /search pages.  Out of scope for this PR are items that originate from /map and /timeline.

This has been tested locally and is currently deployed to staging.  It addresses [ticket #5287](https://issues.dp.la/issues/5287).

### CODE REVIEW

**Comment by AudreyAltman** [comment]
This is no longer on staging, but can be re-deployed for code review purposes if needed.

**Comment by anarchivist** [comment]
Are these params added to the URI for the item being displayed? If so we need to modify our Google Analytics config to ignore them?

When you get a moment, can you redeploy to staging as well? Thanks!

**Comment by AudreyAltman** [comment]
@anarchivist  Good thinking on the Google Analytics config.  I just made the modification in our GA admin dashboard.  Also, this branch has been deployed to staging.

**Comment by anarchivist** [comment]
Excellent. Looks good. Rebase?

**Comment by AudreyAltman** [comment]
rebased to develop

**Pull request merged**
